### ISSUE TITLE
ヘッダーの作成(マークアップのみ)

### ISSUE THREAD

**Issue by daitasu** [daitasu/npo-covid-jp#3]
## 概要
ヘッダー部分のデザイン作成

<img width="500" alt="スクリーンショット 2020-04-11 21 17 24" src="https://user-images.githubusercontent.com/28728602/79043393-dbc01480-7c39-11ea-8f3d-4a8d3fd7ba99.png">

**Comment by Ysy-g54** [comment]
@daitasu ヘッダーのタブとフッターのボタンの内容が同じであれば、並び順を同じにして定数として一か所で管理したほうがいいとおもったんだけど、どうかな?

**Comment by daitasu** [comment]
@Ysy-g54 
ありがとう！
ヘッダーとフッターの内容は、スプレッドシートから情報を引っこ抜いてきて、APIの内容をそのまま流すので、定数ではないかも。
APIからくる前提で、Vuexで管理すると良い気がした！
