### ISSUE TITLE
フッターの作成(マークアップのみ)

### ISSUE THREAD

**Issue by daitasu** [daitasu/npo-covid-jp#4]
## 概要
フッター部分の作成(マークアップのみ)
<img width="500" alt="スクリーンショット 2020-04-11 21 20 28" src="https://user-images.githubusercontent.com/28728602/79043466-496c4080-7c3a-11ea-9959-2b53240d8dcd.png">

**Comment by Ysy-g54** [comment]
@daitasu 
画像の情報ください！！！！ ❤️

**Comment by Ysy-g54** [comment]
@daitasu 
マークアップのみ、ということだから大丈夫?
